events {}

http {
    upstream auth_service {
        server auth-service:5000;
    }

    upstream publication_service {
        server publication-service:5002;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://auth_service$request_uri;
        }

        location /posts {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://publication_service$request_uri;
        }
    }
}