name: Flask Microservices CI (Docker)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Check running containers
        run: docker ps

      - name: Show logs (if needed)
        run: docker compose logs

      - name: Stop services
        if: always()
        run: docker compose down
